#!/usr/bin/env Rscript

#We have a hypothetical population of 2 million individuals with the following conditional probabilities as described below:
#The test is positive 80% of the time when tested on a patient with the disease (high sensitivity): 
#P(test+|disease)=0.80
#The test is negative 95% of the time when tested on a healthy patient (high specificity): 
#P(test−|heathy)=0.95
#The disease is prevalent in about 3.4% of the community: 
#P(disease)=0.034

#Use the following code for our Bayesian Situation
set.seed(1)
disease <- sample(c(0,1), size=2e6, replace=TRUE, prob=c(1-.034,0.034))
test <- rep(NA, 2e6)
test[disease==0] <- sample(c(0,1), size=sum(disease==0), replace=TRUE, prob=c(0.95,0.05))
test[disease==1] <- sample(c(0,1), size=sum(disease==1), replace=TRUE, prob=c(0.20, 0.80))

#What is the probability that a test is positive?
mean(test)

#What is the probability that an individual has the disease if the test is negative?
mean(disease[test==0])

#What is the probability that you have the disease if the test is positive?
mean(disease[test==1]==1)

#If a patient's test is positive, how much does that increase their risk of having the disease?
mean(disease[test==1]==1)/mean(disease==1)
