#!/usr/bin/env Rscript

#Load the data
library(dslabs)
data(tissue_gene_expression)

#Remove the row means and compute the distance between each observation
d <- dist(tissue_gene_expression$x - rowMeans(tissue_gene_expression$x))

#Make a hierarchical clustering plot and add the tissue types as labels
h <- hclust(d)
plot(h)

#Run a k-means clustering on the data with  K=7 . Make a table comparing the identified clusters to the actual tissue types.
cl <- kmeans(tissue_gene_expression$x, centers = 7)
table(cl$cluster, tissue_gene_expression$y)

#Select the 50 most variable genes and make a heatmap
library(RColorBrewer)
sds <- matrixStats::colSds(tissue_gene_expression$x)
ind <- order(sds, decreasing = TRUE)[1:50]
colors <- brewer.pal(7, "Dark2")[as.numeric(tissue_gene_expression$y)]
heatmap(t(tissue_gene_expression$x[,ind]), col = brewer.pal(11, "RdBu"), scale = "row", ColSideColors = colors)

#Plot the first two principal components with color representing tissue type.
pc <- prcomp(tissue_gene_expression$x)
data.frame(pc_1 = pc$x[,1], pc_2 = pc$x[,2], 
			tissue = tissue_gene_expression$y) %>%
	ggplot(aes(pc_1, pc_2, color = tissue)) +
	geom_point()

#What is the correlation between the average of each prediction and the predictions?
avgs <- rowMeans(tissue_gene_expression$x)
data.frame(pc_1 = pc$x[,1], avg = avgs, 
			tissue = tissue_gene_expression$y) %>%
ggplot(aes(avgs, pc_1, color = tissue)) +
	geom_point()
cor(avgs, pc$x[,1])

#Compute the pca after centering
x <- with(tissue_gene_expression, sweep(x, 1, rowMeans(x)))
pc <- prcomp(x)
data.frame(pc_1 = pc$x[,1], pc_2 = pc$x[,2], 
	   tissue = tissue_gene_expression$y) %>%
	   ggplot(aes(pc_1, pc_2, color = tissue)) +
	   geom_point()

#Examine the first 10 Principal componenets
for(i in 1:10){
	boxplot(pc$x[,i] ~ tissue_gene_expression$y, main = paste("PC", i))
}

#Plot the percent variance explained by PC number.
plot(summary(pc)$importance[3,])
