---
title: "R Notebook"
output: html_notebook
---

Trees

Load Library, load data, and Train-Test split
```{r}
library(h2o)
h2o.init()

url <- "http://h2o-public-test-data.s3.amazonaws.com/smalldata/iris/iris_wheader.csv"
iris <- h2o.importFile(url)

parts <- h2o.splitFrame(iris, 0.8, seed =123)
train <- parts[[1]]
test <- parts[[2]]
```

Random Forest Model
```{r}
mRF <- h2o.randomForest(1:4,5, train)
```

```{r}
mRF
```

Random Forest Test Performance 
```{r}
h2o.performance(mRF, test)
```

Gradient Boost Machine
```{r}
mGBM <- h2o.gbm(1:4, 5, train)
mGBM
```

```{r}
h2o.performance(mGBM, test)
```

Import data from data frame to h2o
```{r}
x <- seq(0,10,0.01)
y <- jitter(sin(x), 1000)
```

```{r}
sinewave <- data.frame(a=x, b=y)
sinewave.h2o <- as.h2o(sinewave)
```

Train test val split
```{r}
parts <- h2o.splitFrame(iris,
                        c(0.8,0.1),
          destination_frames = c('train' , 'valid', 'test'),
          seed = 123)
```

```{r}
train <- parts[[1]]
test <- parts[[3]]
valid <- parts[[2]]
```

GBM with cross-validation
```{r}
mGBM_cv <- h2o.gbm(1:4,5, train,
                   model_id = '9foldcv',
                   nfolds = 9)
```

