#!/usr/bin/env Rscript
#What is the probability that the ball will be cyan?

cyan <- 36
magenta <- 55
yellow <- 70
red <- 12

# Assign a variable `p` as the probability of choosing a cyan ball from the box
p = cyan/(cyan+magenta+yellow+red)
p

What is the probability that the first draw is cyan and that the second draw is not cyan?

#probability of choosing a cyan ball from the box on the first draw.
p_1 <- cyan / (cyan + magenta + yellow+red)

#probability of not choosing a cyan ball on the second draw without replacement
p_2 <- (magenta+yellow)/(cyan+magenta+yellow - 1)
p_1*p_2
